load("@rules_clojure//:toolchain.bzl", "clojure_toolchain")

clojure_toolchain(
    name = "clojure_toolchain",
    classpath = [
        "@org_clojure//jar",
        "@org_clojure_spec_alpha//jar",
        "@org_clojure_core_specs_alpha//jar",
    ],
)
