name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run bazel test
        run: bazel test ...
