name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: bazel
      - name: Run bazel build
        run: bazel build //...
      - name: Run bazel test
        run: bazel test //...
