name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: bazel
      - name: Install bazelisk
        run: |
          curl "https://github.com/bazelbuild/bazelisk/releases/download/v1.5.0/bazelisk-linux-amd64" -L -o $HOME/bazelisk
          chmod +x $HOME/bazelisk
      - name: Run bazel test
        run: $HOME/bazelisk test //...
